-- COALESCE
-- TASK
-- FIND THE USER NAME IN THE USER TABLE
-- WHICH CITY THEY ARE FROM 
-- AND THEIR PHONE NUMBER
-- AND IF THE ANY CITY DOES NOT HAVE ANY USER THEN RETUN NULL

SELECT C.city_name AS CityName,COALESCE(U.name,"N/A") AS UserName,COALESCE(U.phone,"N/A") AS PhoneNumber
FROM city C 
LEFT JOIN User_info U 
ON C.city_id = U.CITY_ID; 
