-- UPPER()     -- MAKE UPPER CASE
-- LOWER()     -- MAKE LOWER CASE
-- CONCAT()    -- HOIN TWO VARCHAR / STRING
-- LEFT()      -- TAKE PART OF THE STRING FROM THE LEFT 
-- RIGHT()     -- TAKE PART OF THE STRING FROM THE RIGHT
-- REPLACE()   -- REPLACE 
-- SUBSTRING() -- EXTRACT SUBSTRING FOR A STRING
-- LENGTH()    -- FIIND THE LENGTH OF A STRING
-- TRIM()      -- REMOVE BEGINING OR TRAILING SPACE

SELECT UPPER("Tanvir Rahman");
SELECT LOWER("tanvir RAHman");
SELECT CONCAT("Tanvir"," ","Rahman");
SELECT LEFT("Tanvir",3);
SELECT UPPER(LEFT("Tanvir",3)) AS INITIAL;
SELECT SUBSTRING("Bangladesh",7,10); ## it will return only resh
SELECT RIGHT("Bangladesh",4);
SELECT TRIM("    TANVR RAHMAN     ");
SELECT RTRIM("    TANVR RAHMAN     ");
SELECT LTRIM("    TANVIR RAHMAN");
SELECT REPLACE("Bangladesh","sh","shi");
SELECT LENGTH("BANGLADESH IS A GREAT COUNTRY");