USE food_delivery;

-- FIRST DMS STATEMENT (INSERT)
-- TASK INSERT DATA IN USER_INFO TABLE
-- ADD RECORDS TO THE TABLE
-- INSERT INTO TABLE(COLUMN,COLUMN2) VALUES(VALUE1,VALUE2)
-- COLUMN NAME WRITING IS OPTIONAL BUT IT IS A GOOD PRACTICE
SELECT * FROM User_info;
INSERT INTO User_info VALUES(41,NOW(),"Tanvir Rahman",02554321,"Android",1,1);
SELECT * FROM User_info WHERE ID = 41;

-- WITH COLUMN
INSERT INTO 
	User_info(ID,registration_date,name,phone,operating_system,otp_verified,CITY_ID)
VALUES
    (42,NOW(),"Ornob Rahman",0253354321,"Android",1,1);
    
    
-- UPDATE QUERY
-- Task : UPDATE THE CITY ID from 1 to 2 OF TANVIR RAHMAN USER
UPDATE 
	User_info
SET
	CITY_ID = 2
WHERE
	name = "Tanvir Rahman";
SELECT CITY_ID FROM User_info WHERE name = "Tanvir Rahman";
    
-- DELETE STATEMENT   
-- DELETE IS A ROW BY ROW OPERATION
-- TRUNCATE IS NOT A ROW BY ROW OPERATION
-- ITS A FULL TABLE OPERATION
-- DELETE CAN RECOVER UNLESS IT IS COMMITTED
-- TRUNCATE HAS NO RECOVER 

DELETE FROM User_info
WHERE name = "Tanvir Rahman";

SELECT * FROM User_info;