-- JOIN COMBINE DATA FROM MULTIPLE TABLE
-- BASED ON THE RELATION
-- INNER JOIN
-- OUTER JOIN
-- FULL OUTER JOIN
-- LEFT JOIN
-- RIGHT JOIN
-- UNION
-- UNION ALL
-- AS CLAUSE (COLUMN ALIAS AND TABLE ALIAS)

-- ALIASING (AS)
-- YOU CANT USE ALIAS IN A WHERE CLAUSE
-- YOU HAVE TO USE A PROPER COLUMN NAME
SELECT phone AS PhoneNumber FROM User_info;

-- INNER JOIN
-- JOIN MULTIPLE TABLE AND TAKE ONLY THE COMMON ONE
-- ONLY COMMON VALUE
-- task
-- FIND ALL THE USERS WHO ORDER ATLEAST ONCE
-- EXPLAIN NOT ALL REGISTERED USERS ORDER FOOD
-- SUPPOSE SUM OF THEM JUST REGISTERED BUT NEVER ORDR
-- IF THEY ORDER THEY THERE WILL BE ENTRY AS USER_ID IN THE ORDER
-- TABLE
-- SO WE JOIIN USER_INFO AND ORDERS TABLE AND FIND THEIR NAME AND MOBILE NUMBER 
-- WHO ORDERD
SELECT DISTINCT U.name AS CustomerName,U.phone AS PhoneNumber FROM User_info U
JOIN Orders O 
ON U.ID = O.user_id; 
SELECT COUNT(*) FROM User_info;

-- total user 42 
-- among them 32 are ordered at least once 
-- IN INNER 
 
