USE SAMPLE_SCHEMA;
CREATE TABLE USER_TABLE
	(
		ID 					INT PRIMARY KEY,
        REGISTRATION_DATE 	TIMESTAMP,
        USERNAME 			VARCHAR(50) NOT NULL,
        PHONE_NUMBER		CHAR(11) UNIQUE NOT NULL,
        OPERATING_SYSTEM    VARCHAR(20),
        OTP_VERIFYED        BOOLEAN,
        CITY                VARCHAR(20)
	); 
    
INSERT INTO USER_TABLE
VALUES
	(1,NOW(),'JOHN','12345678','ANDROID',TRUE,'CHITTAGONG'),
    (2,NOW(),'CHARLI','02554321','ANDROID',TRUE,'CHITTAGONG'),
    (3,NOW(),'TONY','01765654','IOS',FALSE,'DHAKA');
    
SELECT * FROM USER_TABLE;

UPDATE USER_TABLE SET OTP_VERIFYED = 1 WHERE USERNAME='TONY';
SELECT * FROM USER_TABLE;

DELETE USER_TABLE  WHERE USERNAME='TONY';
DELETE FROM USER_TABLE;

